apiVersion: apps/v1
kind: Deployment
metadata:
  name: ubuntu-sleep-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ubuntu-sleeper
  template:
    metadata:
      labels:
        app: ubuntu-sleeper
    spec:
      containers:
      - name: ubuntu-container
        image: ubuntu:latest
        command: ["/bin/bash", "-c", "sleep 3600; echo 'Sleep complete, container exiting.'"]
        imagePullPolicy: IfNotPresent
      restartPolicy: Always
